# Generated by Django 2.2.2 on 2019-06-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='vksession',
            name='status',
            field=models.CharField(choices=[('enter address', 'enter address'), ('enter name', 'enter name'), ('start', 'start'), ('allowed', 'allowed'), ('enter org name', 'enter org name'), ('enter role', 'enter role'), ('allowed group', 'allowed group')], default='enter role', max_length=100),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('files', models.ManyToManyField(to='core.CSV_File')),
            ],
        ),
    ]
