# Generated by Django 2.2.2 on 2019-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190615_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_file',
            name='file',
        ),
        migrations.AddField(
            model_name='csv_file',
            name='file_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
