# Generated by Django 2.2.2 on 2019-06-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190615_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vksession',
            name='status',
            field=models.CharField(choices=[('enter address', 'enter address'), ('enter name', 'enter name'), ('start', 'start'), ('allowed', 'allowed'), ('enter org name', 'enter org name'), ('enter role', 'enter role'), ('allowed group', 'allowed group')], default='start', max_length=100),
        ),
    ]
