# Generated by Django 2.2.2 on 2019-06-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190615_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='approved',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='is_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Organisation'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='vk_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vksession',
            name='status',
            field=models.CharField(choices=[('enter address', 'enter address'), ('enter name', 'enter name'), ('start', 'start'), ('allowed', 'allowed'), ('enter org name', 'enter org name'), ('enter role', 'enter role'), ('allowed group', 'allowed group'), ('approve', 'approve'), ('enter user org', 'enter user org')], default='start', max_length=100),
        ),
    ]
